const TTP_PRODUCTS = {
  "cable-system": {
    id: "cable-system",
    name: "TTP Cable System",
    category: "Desk Finds",
    categoryKey: "desk",
    type: "standard",
    badge: "KIT",
    short: "Um kit completo para manter os cabos organizados, acessíveis e fora do caminho.",
    description: "O TTP Cable System reúne várias soluções de organização de cabos num único conjunto, pensado para reduzir a desarrumação sem transformar a secretária numa instalação permanente. Mantém cabos de carregamento acessíveis, organiza fios soltos e facilita o transporte dos cabos que usas fora de casa.",
    price: 34,
    priceLabel: "34€",
    colors: ["Sand", "Graphite", "Soft White", "Build Teal"],
    sizes: [],
    options: ["Kit completo", "Cable Holder 1", "Cable Holder 3", "Cable Holder 5", "Desk Hook", "Portable Cable Winder", "Cable Ties"],
    image: null,
    visual: "cable"
  },
  "cable-box-xl": {
    id: "cable-box-xl",
    name: "TTP Cable Box XL",
    category: "Desk Finds",
    categoryKey: "desk",
    type: "standard",
    short: "Esconde extensões, transformadores e excesso de cabo numa caixa discreta e organizada.",
    description: "A TTP Cable Box XL foi criada para resolver a parte menos bonita de qualquer setup: extensões, carregadores e metros de cabo acumulados. A tampa removível mantém tudo concentrado num único local, mas continua a permitir acesso rápido sempre que precisares de alterar alguma ligação.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Sand", "Graphite", "Soft White"],
    sizes: ["XL"],
    options: [],
    image: null,
    visual: "box"
  },
  "arc-headphone-stand": {
    id: "arc-headphone-stand",
    name: "TTP Arc Headphone Stand",
    category: "Desk Finds",
    categoryKey: "desk",
    type: "standard",
    short: "Um lugar próprio para os teus headphones — sempre acessíveis e organizados.",
    description: "O TTP Arc Headphone Stand transforma os headphones num elemento do próprio setup. A estrutura vertical mantém-nos apoiados, acessíveis e fora do caminho quando não estão a ser utilizados.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Sand", "Graphite", "Soft White", "Build Teal"],
    sizes: [],
    options: [],
    image: null,
    visual: "headphones"
  },
  "hide-headset-hanger": {
    id: "hide-headset-hanger",
    name: "TTP Hide Headset Hanger",
    category: "Desk Finds",
    categoryKey: "desk",
    type: "standard",
    short: "Guarda os headphones por baixo da secretária e recupera espaço no setup.",
    description: "O TTP Hide Headset Hanger aproveita uma zona normalmente desperdiçada. Os headphones ficam fora da superfície de trabalho, mas continuam suficientemente perto para os poderes pegar rapidamente.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Sand", "Graphite", "Soft White"],
    sizes: [],
    options: [],
    image: null,
    visual: "hanger"
  },
  "lift-laptop-stand": {
    id: "lift-laptop-stand",
    name: "TTP Lift Laptop Stand",
    category: "Desk Finds",
    categoryKey: "desk",
    type: "standard",
    short: "Um suporte ajustável para elevar o portátil e organizar melhor o setup.",
    description: "O TTP Lift Laptop Stand eleva o computador relativamente à superfície da secretária, permitindo libertar espaço e criar uma disposição mais limpa. É especialmente útil em setups com teclado, rato e monitor externo.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Sand", "Graphite", "Soft White"],
    sizes: [],
    options: [],
    image: null,
    visual: "laptop"
  },
  "modular-desk": {
    id: "modular-desk",
    name: "TTP Modular Desk System",
    category: "Desk Finds",
    categoryKey: "desk",
    type: "configurable",
    badge: "MODULAR",
    short: "Cria o teu próprio sistema de organização escolhendo apenas os módulos de que precisas.",
    description: "O TTP Modular Desk System é um ecossistema expansível para a secretária. Em vez de comprares um organizador fixo, escolhes os módulos que fazem sentido para o teu setup e podes acrescentar outros mais tarde.",
    price: 19,
    priceLabel: "desde 19€",
    colors: ["Sand", "Graphite", "Soft White", "Build Teal"],
    sizes: [],
    options: ["Pen Holder", "Phone Holder", "Headphone Hanger", "Cable Clip", "Tray", "Storage", "Watch Stand", "MagSafe Mount"],
    image: null,
    visual: "modular"
  },
  "fold-phone-stand": {
    id: "fold-phone-stand",
    name: "TTP Fold Phone Stand",
    category: "Desk Finds",
    categoryKey: "desk",
    type: "standard",
    short: "Compacto quando fechado. Pronto quando precisas.",
    description: "O TTP Fold Phone Stand combina suporte e portabilidade numa peça compacta. Aberto, mantém o smartphone numa posição confortável para vídeos, chamadas ou utilização ao lado do computador. Fechado, ocupa muito pouco espaço.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Sand", "Graphite", "Soft White", "Build Teal", "Print Coral"],
    sizes: [],
    options: [],
    image: null,
    visual: "phone"
  },
  "hidden-drawers": {
    id: "hidden-drawers",
    name: "TTP Hidden Drawers",
    category: "Desk Finds",
    categoryKey: "desk",
    type: "standard",
    short: "Transforma o espaço debaixo da secretária em armazenamento escondido.",
    description: "As TTP Hidden Drawers permitem guardar cabos, pens USB, cartões, adaptadores e pequenos acessórios sem ocupar espaço em cima da mesa.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Sand", "Graphite", "Soft White"],
    sizes: ["Slim Single", "Slim Double", "Slim Triple", "Big Single", "Big Double", "Slim Stack", "Slim Square", "Pico"],
    options: [],
    image: null,
    visual: "drawers"
  },
  "flow-vase": {
    id: "flow-vase",
    name: "TTP Flow Vase",
    category: "Home & Decor",
    categoryKey: "home",
    type: "standard",
    short: "Um vaso de linhas fluidas que funciona tão bem com flores como sozinho.",
    description: "O TTP Flow Vase explora formas e texturas que só a impressão 3D permite criar facilmente. As linhas contínuas dão movimento à peça e tornam-na num objeto decorativo por si só.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Soft White", "Sand", "Graphite", "Build Teal", "Print Coral"],
    sizes: ["S", "M", "L"],
    options: [],
    image: null,
    visual: "vase"
  },
  "leaf-coaster-set": {
    id: "leaf-coaster-set",
    name: "TTP Leaf Coaster Set",
    category: "Home & Decor",
    categoryKey: "home",
    type: "standard",
    short: "Quatro bases inspiradas em folhas acompanhadas pelo seu próprio suporte.",
    description: "O TTP Leaf Coaster Set transforma um objeto quotidiano numa pequena peça de decoração. Quando não estão a ser utilizadas, as quatro bases encaixam no suporte dedicado e ficam arrumadas.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Sand", "Build Teal", "Soft White", "Graphite"],
    sizes: [],
    options: [],
    image: null,
    visual: "leaf"
  },
  "monstera": {
    id: "monstera",
    name: "TTP Monstera Coaster Plant",
    category: "Home & Decor",
    categoryKey: "home",
    type: "standard",
    badge: "TTP PICK",
    short: "Bases para copos que, guardadas, se transformam numa pequena Monstera decorativa.",
    description: "Cada coaster funciona como uma folha. Depois de utilizado, volta a encaixar na estrutura central e o conjunto transforma-se novamente numa pequena planta Monstera dentro do seu vaso.",
    price: 42,
    priceLabel: "42€",
    colors: ["Build Teal", "Sand", "Soft White"],
    sizes: [],
    options: [],
    image: "assets/products/monstera/monstera-main.jpg",
    visual: "monstera"
  },
  "amp-pick-holder": {
    id: "amp-pick-holder",
    name: "TTP Amp Pick Holder",
    category: "Music",
    categoryKey: "music",
    type: "standard",
    short: "Um mini amplificador transformado num suporte para palhetas de guitarra.",
    description: "O TTP Amp Pick Holder traz a estética de um amplificador clássico para a secretária ou espaço de música. As palhetas deixam de andar perdidas e passam a ter um lugar próprio.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Graphite", "Print Coral", "Soft White"],
    sizes: [],
    options: [],
    image: null,
    visual: "amp"
  },
  "piano-key-holder": {
    id: "piano-key-holder",
    name: "TTP Piano Key Holder",
    category: "Music",
    categoryKey: "music",
    type: "standard",
    short: "Um porta-chaves para quem quer música até à porta de casa.",
    description: "O TTP Piano Key Holder transforma as formas imediatamente reconhecíveis das teclas de piano num objeto funcional para a entrada de casa.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Soft White + Graphite"],
    sizes: [],
    options: [],
    image: null,
    visual: "piano"
  },
  "your-name": {
    id: "your-name",
    name: "TTP Your Name",
    category: "Personalized",
    categoryKey: "personalized",
    type: "personalized",
    badge: "PERSONALIZADO",
    short: "O teu nome, palavra ou pequena mensagem transformados numa peça feita especialmente para ti.",
    description: "O TTP Your Name transforma texto numa pequena peça decorativa tridimensional para secretária, estante, quarto ou espaço de trabalho. Cada unidade é criada especificamente para o texto escolhido.",
    price: null,
    priceLabel: "Preço em breve",
    colors: ["Soft White", "Graphite", "Sand", "Build Teal", "Momentum Yellow", "Print Coral"],
    sizes: ["S", "M", "L"],
    options: [],
    image: null,
    visual: "name"
  },
  "mini-me": {
    id: "mini-me",
    name: "TTP Mini Me",
    category: "Personalized",
    categoryKey: "personalized",
    type: "mini-me",
    badge: "PERSONALIZADO",
    short: "Fotografias, hobbies e personalidade transformados numa figura 3D única.",
    description: "O TTP Mini Me transforma fotografias e pequenas histórias sobre uma pessoa numa figura criada especialmente para ela.",
    price: 59,
    priceLabel: "desde 59€",
    colors: [],
    sizes: [],
    options: ["POP", "STYLIZED"],
    image: null,
    visual: "mini-me",
    url: "mini-me.html"
  }
};

const TTP_CATEGORIES = [
  { key: "all", label: "Todos" },
  { key: "desk", label: "Desk Finds" },
  { key: "home", label: "Home & Decor" },
  { key: "personalized", label: "Personalized" },
  { key: "music", label: "Music" },
  { key: "collections", label: "Collections" }
];

const TTP_COLORS = {
  "Soft White": "#FFFFFF",
  "Graphite": "#1B1F24",
  "Sand": "#D2B48C",
  "Build Teal": "#0083A6",
  "Momentum Yellow": "#FFD21A",
  "Print Coral": "#FF6B4A",
  "Soft White + Graphite": "linear-gradient(90deg,#fff 0 50%,#1B1F24 50%)"
};
